// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from helloworld.djinni

#pragma once

#include <memory>
#include <string>

namespace helloworld {

class HelloWorld {
public:
    virtual ~HelloWorld() = default;

    static /*not-null*/ std::shared_ptr<HelloWorld> create();

    virtual std::string get_hello_world() = 0;
};

} // namespace helloworld
