// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from helloworld.djinni

#pragma once

#include <memory>
#include <string>

class HelloWorld {
public:
    virtual ~HelloWorld() {}

    static std::shared_ptr<HelloWorld> create();

    virtual std::string get_hello_world() = 0;
};
